### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by stefanodvx** [IcySnex/InstaTracker#1]
(iOS) I'm trying to fetch an account data. the counter is 1000 followers, but instead i get like 900-800 accounts back, same goes for following. i've already set all the right limits. The user I'm trying to track got 1000 followers and 100 following.
![IMG_4282](https://github.com/IcySnex/InstaTracker/assets/69367859/e30cedc9-aca0-4ba5-9035-c36a9efa35c3)

**Comment by IcySnex** [comment]
I also faced this problem when trying to fetch the data of an account with a lot of followers/following while debugging.
I have looked into this issue but it seems like the Instagram API wrapper or the official Instagram Android API is the problem.

I have checked the issues of the Instagram API wrapper. If youre interested you can check these:
https://github.com/ramtinak/InstagramApiSharp/issues/516
https://github.com/ramtinak/InstagramApiSharp/issues/207#issuecomment-471729839
The authors response was: `"I don't think this is related to this library, I think it's related to Instagram, because this library only parses what Instagram API respond to it and it doesn't remove anything from the items (users)."`

InstaTracker itself doesnt modify anything about the followers/following it gets by the API except it removes any duplicates in the list since it also was an issue with the Instagram API and it was quite annoying seeing the same accounts repeated in the list.
You could try to disable this behavior and recompiling it but I am pretty sure it will result in more weird bugs [(Source Code)](https://github.com/IcySnex/InstaTracker/blob/main/InstaTracker/InstaTracker/Services/InfoManager.cs#L79).

Sadly I am not able to fix this bug. If you have any questions, please feel free to ask.

**Comment by IcySnex** [comment]
Since it looks like this issue is inactive now, I will close it. Feel free to reopen this if you have any other questions.
